source 'https://rubygems.org'

ruby '2.1.1'
#ruby-gemset=citysdk

gem 'rdf-turtle'
gem 'sinatra', require: 'sinatra/base'

group :development do
  gem 'capistrano', '~>2.14.1'
  gem 'capistrano-ext', '~>1.2.1'
  gem 'rerun'
  gem 'thin'
end

