# encoding: utf-8

require_relative 'get'
require_relative 'layers/get'
require_relative 'layers/layer/get'
require_relative 'layers/layer/post'
require_relative 'layers/layer/delete'
require_relative 'layers/layer/data/get'
require_relative 'layers/layer/keys/get'
require_relative 'layers/layer/ldprops/post'
require_relative 'layers/layer/periodic/post'
require_relative 'layers/layer/stats/get'
require_relative 'layers/layer/upload/post'
require_relative 'layers/layer/upload/get'
require_relative 'layers/layer/webservice/post'
require_relative 'layers/new/post'
require_relative 'layers/new/get'
require_relative 'prefixes/get'
require_relative 'prefixes/prefix/delete'
require_relative 'uploaded_file_headers/post'

