source 'https://rubygems.org'

ruby '2.1.1'
#ruby-gemset=citysdk

gem 'sinatra', require: 'sinatra/base'
gem 'redcarpet'

group :development do
  gem 'capistrano', '~>2'
  gem 'capistrano-ext'
  gem 'rerun'
  gem 'thin'
end

