# encoding: utf-8

class CitySDKAPI < Sinatra::Application
  GEOMETRY_TYPE_POINT   = 'point'
  GEOMETRY_TYPE_LINE    = 'line'
  GEOMETRY_TYPE_POLYGON = 'polygon'

  GEOMETRY_TYPES = [
    GEOMETRY_TYPE_POINT,
    GEOMETRY_TYPE_LINE,
    GEOMETRY_TYPE_POLYGON
  ]

  CREATE_TYPE_UPDATE = 'update'
  CREATE_TYPE_ROUTES = 'routes'
  CREATE_TYPE_CREATE = 'create'

  CREATE_TYPES = [
    CREATE_TYPE_UPDATE,
    CREATE_TYPE_ROUTES,
    CREATE_TYPE_CREATE
  ]

  DEFAULT_RADIUS = 250
end # class

