source 'https://rubygems.org'

ruby '1.9.3'
#ruby-gemset=citysdk

gem 'active_support'
gem 'amatch'
gem 'base62'
gem 'dalli'
gem 'faraday'
gem 'i18n'
gem 'logger'
gem 'pg'
gem 'racksh'
gem 'rgeo'
gem 'rgeo-geojson'
gem 'sequel'
gem 'sinatra', :require => 'sinatra/base'
gem 'sinatra-sequel'
gem 'stringex'
gem 'yajl-ruby'

group :development do
  gem 'capistrano'
  gem 'capistrano-ext'
end

