source 'https://rubygems.org'

ruby '2.1.1'
#ruby-gemset=citysdk

gem 'docopt'
gem 'pg'
gem 'sequel'
gem 'sinatra-authentication', git: 'https://github.com/foxdog-studios/sinatra-authentication.git'
gem 'sinatra-sequel'

