source 'https://rubygems.org'

ruby '1.9.3'
#ruby-gemset=citysdk

gem 'active_support'
gem 'faraday'
gem 'i18n'
gem 'logger'
gem 'multipart-post'
gem 'pg'
gem 'pony'
gem 'rgeo'
gem 'rgeo-geojson'
gem 'sequel'
gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-sequel'
gem 'sinatra-session'

gem 'citysdk', path: './vendor/citysdk'

group :development do
  gem 'capistrano', '~>2'
  gem 'capistrano-ext'
  gem 'thin'
end

