source 'https://rubygems.org'

ruby '2.1.2'
#ruby-gemset=citysdk

gem 'activesupport'
gem 'citysdk', git: 'https://github.com/foxdog-studios/citysdk.git'
gem 'citysdk-client', git: 'https://github.com/foxdog-studios/citysdk-client.git'
gem 'faraday'
gem 'haml'
gem 'i18n'
gem 'logger'
gem 'multipart-post'
gem 'pg'
gem 'pony'
gem 'rack-flash3'
gem 'rgeo'
gem 'rgeo-geojson'
gem 'sequel'
gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-authentication', git: 'https://github.com/foxdog-studios/sinatra-authentication.git'
gem 'sinatra-sequel'
gem 'sinatra-session'

group :development do
  gem 'capistrano', '~>2'
  gem 'capistrano-ext'
  gem 'racksh'
  gem 'rerun'
  gem 'thin'
end

