source 'https://rubygems.org'

ruby '1.9.3'

#ruby-gemset=citysdk

gem 'activesupport'
gem 'citysdk', git: 'https://github.com/foxdog-studios/citysdk'
gem 'citysdk-client', git: 'https://github.com/foxdog-studios/citysdk-client'
gem 'faraday'
gem 'haml'
gem 'i18n'
gem 'logger'
gem 'multipart-post'
gem 'pg'
gem 'pony'
gem 'rgeo'
gem 'rgeo-geojson'
gem 'sequel'
gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-authentication'
gem 'sinatra-sequel'
gem 'sinatra-session'

group :development do
  gem 'capistrano', '~>2'
  gem 'capistrano-ext'
  gem 'rerun'
  gem 'thin'
end

